FROM python:3.12-slim

RUN pip install --no-cache-dir boto3 psycopg2-binary requests python-dotenv

WORKDIR /app

COPY scripts/ /app/scripts/
COPY profiles/ /app/profiles/

CMD ["python", "/app/scripts/setup_aws.py"]

